package com.hyeonwoo.compose_cocktail_recipes.model


import com.google.gson.annotations.SerializedName

data class Drink(
    val dateModified: String?,
    val idDrink: String?,
    val strAlcoholic: String?,
    val strCategory: String?,
    val strCreativeCommonsConfirmed: String?,
    val strDrink: String?,
    val strDrinkAlternate: String?,
    val strDrinkThumb: String?,
    val strGlass: String?,
    val strIBA: String?,
    val strImageAttribution: String?,
    val strImageSource: String?,
    val strIngredient1: String?,
    val strIngredient2: String?,
    val strIngredient3: String?,
    val strIngredient4: String?,
    val strIngredient5: String?,
    val strIngredient6: String?,
    val strIngredient7: String?,
    val strIngredient8: String?,
    val strIngredient9: String?,
    val strIngredient10: String?,
    val strIngredient11: String?,
    val strIngredient12: String?,
    val strIngredient13: String?,
    val strIngredient14: String?,
    val strIngredient15: String?,
    val strInstructions: String?,
    val strInstructionsDE: String?,
    val strInstructionsES: String?,
    val strInstructionsFR: String?,
    val strInstructionsIT: String?,
    @SerializedName("strInstructionsZH-HANS")
    val strInstructionsZHHANS: String?,
    @SerializedName("strInstructionsZH-HANT")
    val strInstructionsZHHANT: String?,
    val strMeasure1: String?,
    val strMeasure2: String?,
    val strMeasure3: String?,
    val strMeasure4: String?,
    val strMeasure5: String?,
    val strMeasure6: String?,
    val strMeasure7: String?,
    val strMeasure8: String?,
    val strMeasure9: String?,
    val strMeasure10: String?,
    val strMeasure11: String?,
    val strMeasure12: String?,
    val strMeasure13: String?,
    val strMeasure14: String?,
    val strMeasure15: String?,
    val strTags: String?,
    val strVideo: String?
)
fun DummyDrink(): Drink {
    return Drink(
        idDrink = "11728",
        strDrink = "Martini",
        strDrinkAlternate = null,
        strTags = null,
        strVideo = "https://www.youtube.com/watch?v=ApMR3IWYZHI",
        strCategory = "Cocktail",
        strIBA = "unforgettables",
        strAlcoholic = "Alcoholic",
        strGlass = "Cocktail glass",
        strInstructions = "traight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.",
        strInstructionsES = null,
        strInstructionsDE = null,
        strInstructionsFR = null,
        strInstructionsIT = null,
        strInstructionsZHHANS = null,
        strInstructionsZHHANT = null,
        strDrinkThumb = "https://www.thecocktaildb.com/images/media/drink/71t8581504353095.jpg",
        strIngredient1 = "Gin",
        strIngredient2 = "Dry Vermouth",
        strIngredient3 = "Olive",
        strIngredient4 = null,
        strIngredient5 = null,
        strIngredient6 = null,
        strIngredient7 = null,
        strIngredient8 = null,
        strIngredient9 = null,
        strIngredient10 = null,
        strIngredient11 = null,
        strIngredient12 = null,
        strIngredient13 = null,
        strIngredient14 = null,
        strIngredient15 = null,
        strMeasure1 = "1 2/3 oz",
        strMeasure2 = "1/3 oz",
        strMeasure3 = "1",
        strMeasure4 = null,
        strMeasure5 = null,
        strMeasure6 = null,
        strMeasure7 = null,
        strMeasure8 = null,
        strMeasure9 = null,
        strMeasure10 = null,
        strMeasure11 = null,
        strMeasure12 = null,
        strMeasure13 = null,
        strMeasure14 = null,
        strMeasure15 = null,
        strImageSource = null,
        strImageAttribution = null,
        strCreativeCommonsConfirmed = "No",
        dateModified = "2017-09-02 12:51:35"
    )
}