name: Android CI

on:
  push:
    branches: [ 'main', 'release' ]
  pull_request:
    branches: [ 'main', 'release' ]

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle # or app/build.gradle.kts 
        versionCode: ${{github.run_number}}
        versionName: ${{github.run_number}}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  
  release:
    if: contains(github.ref, 'release')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: test
      run: echo "hello world" 
      
